### ISSUE TITLE
Add support for distributed tracing

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-js-base#32]
Work is underway to add support for distributed tracing to the API/server:
* https://github.com/elastic/apm-server/issues/913
* https://github.com/elastic/apm-server/issues/968

Tasks:
- [x] [Set the page load traceId, spanId and sampled from configuration options](https://github.com/elastic/apm-agent-js-base/issues/75)
- [x] Document config options and cross-origin guide for the servers
- [x] Document responding to OPTIONS request
- [x] Document sampling transactions
- [x] Adopt new traceparent flags
- [x] Add tests with a backend agent
- [x] Add whitelist for origins
- [x] Resolve cross-origin issue with the `elastic-apm-traceparent` header (whitelist domains) -> Needs more investigation
- [x] Add the header to unsampled transaction
- [x] [Implement sampling](https://github.com/elastic/apm-agent-js-base/issues/49)
- [x] [Investigate Chrome Mobile test failure](https://github.com/elastic/apm-agent-js-base/issues/62)
- [x] Add a configuration option to set trace id
- [x] Add tests for XHR patch 
- [x] Implement correct id format for DT
- [x] Use correct formats for Transaction, Span and Error Ids
- [x] Add the header to the same origin requests
- [x] Generate Trace Id

Global DT checklist:
- [x] update opbean-frontend to include a distributed tracing call 
- [x] intake protocol v2
- [x] [test that responses from the server during chunked writes](https://github.com/elastic/apm-server/issues/1298#issuecomment-415704054) work with the client you’re using (if your agent uses chunked writes)
- [x] `transaction.span_count.started` (https://github.com/elastic/apm-server/issues/1241)

Related:
* [Backend agents should document how to respond to the OPTIONS request](https://github.com/elastic/apm-dev/issues/325)

**Comment by jahtalab** [comment]
Initial idea: to add `Elastic-Apm-Traceparent` to the same origin request, and have whitelist of others

**Comment by alvarolobato** [comment]
@jahtalab I've added some items to the initial checklist from the global DT checklist, some may not be applicable to RUM, like the chuncked writes test feel free to remove it.

**Comment by jahtalab** [comment]
Thanks @alvarolobato! 

Would you please elaborate on "auto-instrument http module(s) to use extact/inject functionality" and "traceparent header extract/inject functionality".

Also the only required property under `spant_count` is `transaction.span_count.started` which has been added already. Did you mean to say  `transaction.span_count.started`?

**Comment by jahtalab** [comment]
I see, "auto-instrument http module(s) to use extact/inject functionality" doesn't apply to the RUM agent since we don't accept incoming http requests. But we do inject the `elastic-apm-traceparent` header into outgoing http requests and since we do it at the browser level, we don't have to instrument each http module separately. 

As far as I understand the two bullets are the same, am I missing something?

**Comment by alvarolobato** [comment]
No you are not, I think both things are already done on your side.

**Comment by roncohen** [comment]
great job @jahtalab ! 🎉🎉🎉
